### ISSUE TITLE
How to use BToast

### ISSUE THREAD

**Issue by susanne99** [bootstrap-vue-next/bootstrap-vue-next#1396]
i am using v 0.9.23, with typescript !

this doesn't work, because this.$bvToast does not exists, ilke in bootstrap-vue
```
this.$bvToast.toast('Toast body content', {
        title: 'Toast test',
        variant: 'succes',
        solid: true
      })

```
and this, dos not also work:
```
import { useToast } from 'bootstrap-vue-next';
export default defineComponent({
    name: 'testcomp',

    setup: () => ({ toast: useToast() }),

anywhere in a method:
     const content: ToastContent = {title:'this is title', body:this.notificationmsg.text}
     this.toast?.show(content)

```

in the documentation i did not found an example
thanks in advance for your help

**Comment by IGx89** [comment]
I don't believe toasts currently work, unfortunately. See https://github.com/bootstrap-vue-next/bootstrap-vue-next/discussions/1311

**Comment by susanne99** [comment]
yes I believe that too. 
but most of it is already implemented, 
not much is missing anymore. 
too bad, I don't want to install extra vue3-toastify now. 
where are the developers, give yourself a push, then a great standard feature would be implemented

**Comment by susanne99** [comment]
in file BToast/plugin.ts in function useToast() the controller in line 215 is always undefined
```

export function useToast(vm?: any, key: symbol = injectkey): ToastInstance | undefined {
  //let's get our controller to fetch the toast instance - it is always undefined !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  const controller = inject(getKey()) as ToastController

  // not parameters passed, use root if defined
  if (!vm) {
    return new ToastInstance(controller.getOrCreateViewModel())
  }

  // use toast generically
  const vm_id = {id: Symbol('toastInstance')}
  const local_vm: ToastVM = {...defaults, ...vm_id, ...vm}
  const vm_instance = controller.getOrCreateViewModel(local_vm)
  return new ToastInstance(vm_instance)
}
```

**Comment by tada5hi** [comment]
You have to insert the `BContainer` component somewhere in the root tree.

```vue
<template>
<BContainer
            :toast="{root: true}"
            fluid="sm"
            position="position-fixed"
            style="z-index: 9999"
        />
</template>
```

**Comment by susanne99** [comment]
when i do your suggestion, then i get immediately this error

```
plugin.ts:221  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getOrCreateViewModel')
    at Bn (plugin.ts:221:34)
    at setup (BContainer.vue:47:23)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7236:25)
    at setupComponent (runtime-core.esm-bundler.js:7197:36)
    at mountComponent (runtime-core.esm-bundler.js:5599:7)
    at processComponent (runtime-core.esm-bundler.js:5565:9)
    at patch (runtime-core.esm-bundler.js:5040:11)
    at mountChildren (runtime-core.esm-bundler.js:5284:7)
    at processFragment (runtime-core.esm-bundler.js:5499:7)
```

why BContainer, i think BToaster and BToast are the right components.
Programmatically i use:
```
 const content: ToastContent = {title:'das ist der title', body:this.notificationmsg.text}
 const t = useToast()
 t?.show(content)
```
or this version:

```
import { useToast } from 'bootstrap-vue-next';

setup: () => ({ toast: useToast() }),

 const content: ToastContent = {title:'das ist der title', body:this.notificationmsg.text}
 this.toast?.show(content)
```

**Comment by Avarow** [comment]
I made it work using the following code 

main.ts
```
import App from "@/App.vue";
import { BToastPlugin } from "bootstrap-vue-next";
const app = createApp(App);
app.use(BToastPlugin);
```

Component.vue

Template
```
<BContainer :toast="{ root: true }" fluid="sm" position="position-fixed">
        <BToaster name="b-toaster-top-right" class="b-toaster position-fixed p-3"></BToaster>
</BContainer>
```


Script
```
import { useToast } from "bootstrap-vue-next"
const bToast = useToast();
const showToast = () => {
    const toast = bToast!.danger({ title: "test title", body: "test body" }, {
        autoHide: false,
        noCloseButton: false,
        delay: 5000,
        pos: "top-right",
        variant: "danger"
    });
}
```

However, styling does not work at all, color variants are not applied and I got a black square instead of close button.

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/37325968/c5922e65-26f0-4a41-b103-27125f46f9b3)

probably related to https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1219

**Comment by susanne99** [comment]
Thank you for your commitment. 
But there are still only work arounds, 
I want the original solution. 
I currently have an "Alert" solution

**Comment by xvaara** [comment]
@susanne99 It seems you're not using the toast plugin.

here's an example: https://stackblitz.com/edit/vitejs-vite-dkhmnh?file=src%2Fmain.js,src%2FApp.vue

look at the main.js
