### ISSUE TITLE
BCollapse throwning an error [Vue warn]: Failed to resolve directive: b-toggle

### ISSUE THREAD

**Issue by ymarynych** [bootstrap-vue-next/bootstrap-vue-next#1637]
I recently installed a new init Nuxt3-project by running following:
`npx nuxi@latest init <project-name>`

Then installed bootstrap-vue-next by running following:
`npm i bootstrap bootstrap-vue-next @bootstrap-vue-next/nuxt -D`

Then added these lines to the nuxt.config.ts:
`// nuxt.config.js/ts
export default defineNuxtConfig({
  modules: ['@bootstrap-vue-next/nuxt'],
  css: ['bootstrap/dist/css/bootstrap.min.css'],
})`

But as soon as I'm adding the BCollapse elements to the page (from the docs) 

`<BButton v-b-toggle.collapse-1 variant="primary">Toggle Collapse</BButton>

<BCollapse id="collapse-1">
  <BCard>
    <p class="card-text">Collapse contents Here</p>
    <BButton v-b-toggle.collapse-1-inner size="sm">Toggle Inner Collapse</BButton>
    <BCollapse id="collapse-1-inner" class="mt-2">
      <BCard>Hello!</BCard>
    </BCollapse>
  </BCard>
</BCollapse>`

It throws me following errors
`[Vue warn]: Failed to resolve directive: b-toggle
[nitro] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'getSSRProps')
    at Module.ssrGetDirectiveProps (C:\MyDocs\Work\test-bootstrap-vue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:468:40)
    at _sfc_ssrRender (C:\MyDocs\Work\test-bootstrap-vue\app.vue:35:149)
    at renderComponentSubTree (C:\MyDocs\Work\test-bootstrap-vue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:683:9)
    at renderComponentVNode (C:\MyDocs\Work\test-bootstrap-vue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:631:12)
    at Module.ssrRenderComponent (C:\MyDocs\Work\test-bootstrap-vue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:86:10)
    at default (C:\MyDocs\Work\test-bootstrap-vue\node_modules\nuxt\dist\app\components\nuxt-root.vue:79:37)
    at Module.ssrRenderSuspense (C:\MyDocs\Work\test-bootstrap-vue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:461:5)
    at _sfc_ssrRender (C:\MyDocs\Work\test-bootstrap-vue\node_modules\nuxt\dist\app\components\nuxt-root.vue:70:25)
    at renderComponentSubTree (C:\MyDocs\Work\test-bootstrap-vue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:683:9)
    at renderComponentVNode (C:\MyDocs\Work\test-bootstrap-vue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:631:12)`

HOWEVER, when I'm trying to create minimal reproduction at SlackBlitz it works without any errors.
I assume that might be due to earlier version of bootstrap-vue-next installed in the SlackBlitz

**Comment by VividLemon** [comment]
https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs.html#nuxt-and-directives

> Directives should be imported directly from the bootstrap-vue-next package.

This is something that people probably normally wouldn't expect. But directives are _runtime only_. They can't be processed on the server as they almost always modify the DOM. Subsequently, I can't add them to the auto imports as those imports expect an SSR environment. Perhaps I'm wrong, but it could be worth for someone to see if other packages are able to auto import their directives. Perhaps it is possible and I'm just not sure how to do it in a nuxt-module
