### ISSUE TITLE
Nuxt 3 [500] defineNuxtPlugin is not defined

### ISSUE THREAD

**Issue by nasserbinlaboun** [bootstrap-vue-next/bootstrap-vue-next#1741]
### Describe the bug

when upgrade the package and trying to run the project it shows this error:

[nuxt] [request error] [unhandled] [500] defineNuxtPlugin is not defined
 at ./node_modules/@bootstrap-vue-next/nuxt/dist/runtime/plugins/createBootstrap.mjs:3:1  
 at async ViteNodeRunner.runModule (./node_modules/vite-node/dist/client.mjs:362:5)  
 at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:346:5)  
 at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:189:14)  
 at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:233:12)  
 at async ./virtual:nuxt:/.../.nuxt/plugins/server.mjs:10:31  
 at async ViteNodeRunner.runModule (./node_modules/vite-node/dist/client.mjs:362:5)  
 at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:346:5)  
 at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:189:14)  
 at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:233:12)

### Reproduction

- Upgrde Package to 0.16.0 then run the project

### Used Package Manager

yarn

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alrico88** [comment]
Happening to me too.

Here's a simple reproduction using one of the Nuxt.new templates

https://stackblitz.com/edit/github-khkjcl?file=nuxt.config.ts
